### PR TITLE
Update `theme-i18n.json`

### PR DESCRIPTION
**Pull request by swissspidy**
~We really need a better way to keep this file in sync with core.~ Edit: forgot that we fetch directly from svn

### CODE REVIEW

**Comment by oandregal** [comment]
I've compared the changes with core and it looks good. I'm trying to find the tests instructions in older PRs.

**Comment by oandregal** [comment]
This is what I've done for testing (updated from https://github.com/wp-cli/i18n-command/pull/306):

- Check out this PR locally and cd to the directory.
- `composer install`
- Update the `THEME_JSON_SOURCE` to be empty in [this line](https://github.com/wp-cli/i18n-command/blob/3a18b5e5f3a1d231938da4669c1ea629e063f68a/src/JsonSchemaExtractor.php#L18) at the `JsonSchemaExtractor` class, so the command uses the local backup file defined by `THEME_JSON_FALLBACK`.
- Create a new directory called `foo-theme` that contains a `theme.json` file and paste the content of [TwentyTwentyThree's theme.json](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-content/themes/twentytwentythree/theme.json).
- Run `vendor/bin/wp i18n make-pot foo-theme`
- Verify that there's a `foo-theme/foo-theme.pot` file and that strings and their context are present (look for "Custom template name", "Template part name", "Font family name", "Space size name", the ones added in this PR).

**Comment by swissspidy** [comment]
Awesome, thanks for testing! 🎉 

Totally forgot that this is just the backup file. That makes the change way less urgent 🙂 

I'll see if I can reproduce that test failure locally.

**Comment by schlessera** [comment]
> We really need a better way to keep this file in sync with core.
We can add a GHA that replaces the included file with the one on SVN and creates a PR if changes have been detected.

**Comment by swissspidy** [comment]
@schlessera Good idea. Just added such a workflow now.

**Review by danielbachhuber — APPROVED** [review]

**Pull request merged**
