### PR TITLE
Scan for esc_xml_*() l10n helpers.

### PR DESCRIPTION
**Pull request by pbiron**
Addresses #220.

This the first time I've looked at the `i18n make-pot` code, so I'm not positive this PR does what I think it does :-)

I looked at the existing unit tests and couldn't figure out how to add a test for `esc_xml__()`, etc.  Pointers on how to write that test greatly appreciated.

### CODE REVIEW

**Comment by swissspidy** [comment]
Most of the functionality is covered by Behat tests, not unit tests. Those should be rather self explanatory.

**Comment by pbiron** [comment]
> Most of the functionality is covered by Behat tests, not unit tests. Those should be rather self explanatory.

maybe self explanatory if I knew how to write behat tests :-)  I'll guess I'll have to learn.

**Comment by swissspidy** [comment]
@pbiron You can basically just amend this part with `esc_xml__` & co:

https://github.com/wp-cli/i18n-command/blob/b2ebd7673b82add513cf864c15a06c88b8749b92/features/makepot.feature#L344-L398

Copy & paste :-)

**Comment by pbiron** [comment]
the behat tests have been updated and, yeah, travis was happy...so I guess I did the mods correctly :-)

**Comment by schlessera** [comment]
Released via https://github.com/wp-cli/i18n-command/releases/tag/v2.2.5

**Pull request merged**
