### PR TITLE
Add file references for plugin/theme headers

### LINKED ISSUE #376: Consider adding file reference for strings extracted from file headers
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Context:

* https://github.com/swissspidy/preferred-languages/issues/883
* https://meta.trac.wordpress.org/ticket/7376

Since there is no file reference for strings extracted from plugin/theme headers, it's easy to miss where they're from.

This was originally not added to keep feature parity with the old make-pot tool, but it seems reasonable to add.

**Describe the solution you'd like**

Add source file reference for things like plugin descriptions to avoid issues like the above.

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #376

### CODE REVIEW

**Comment by swissspidy** [comment]
FYI @ocean90 — would like to know if you think this makes sense or not.

**Review by ocean90 — APPROVED** [review]
LGTM.

Would be nice to have the line numbers as well but not a blocker for me.

**Comment by swissspidy** [comment]
Yeah I thought about that as well. Always thought that requires a more complex solution (see #65) but maybe using `PREG_OFFSET_CAPTURE` would suffice (see [this SO post](https://stackoverflow.com/questions/4730867/get-line-number-from-preg-match-all)). I'll see how feasible it is and otherwise will file a follow-up issue.

**Comment by swissspidy** [comment]
@wp-cli/committers would appreciate a quick review here so I can merge this

**Review by danielbachhuber — APPROVED** [review]

**Pull request merged**
