### PR TITLE
Investigate include/exclude oddities

### PR DESCRIPTION
**Pull request by swissspidy**
I've tried replicating #172 with the similar setup:

```
- test.php
- vendor/
- vendor/test.php
```

I ran:

```
vendor/bin/wp i18n make-pot /tmp/wp-i18n-test --debug --include=/vendor/test.php
```

And the `vendor/test.php` file was **not** included as expected.

Then I added 763941ad420d9448c51de738a9a40863d87cf362 and the file was now **included** as expected.

However, I failed at verifying this with a PHPUnit test.

### CODE REVIEW

**Comment by schlessera** [comment]
I looked into the tests, and for the failing test, the function to extract the files returns an empty array. I'll take a closer look at the code now.

**Comment by schlessera** [comment]
From what I can see on my system, this change does nothing, the strings that get passed into that method never contain a leading slash for the tests you are doing...

**Comment by schlessera** [comment]
@swissspidy Can you take a look at the code change I made to validate?

What I found is that the logic that was in place include directories that had files that might match ... but excluded the actual files that would have matched.

**Comment by schlessera** [comment]
Okay, it's obviously not enough to have the unit tests pass...

**Comment by BartvanS** [comment]
I updated my wp-cli and wp cli i18n. Sadly if i recreate this scenario i still only get the translations from the test.php and not the vendor/test.php.
$ wp cli  version -> 2.3.0
I installed the latest version of wp i18n with: 
$ wp package install git@github.com:wp-cli/i18n-command.git

**Comment by swissspidy** [comment]
@BartvanS What command are you running?

**Comment by BartvanS** [comment]
wp i18n make-pot ./ ./test.pot --ignore-domain --include=/vendor/test.php

**Comment by schlessera** [comment]
@BartvanS Do you maybe have the `wp-cli/i18n-command` package installed as an external package as well? You can check this via `wp package list`.

**Pull request merged**
